name: Build Artifacts

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    uses: doriaxengine/doriax-project-example-ci/.github/workflows/build-project.yml@v1
    with:
      title: Character Control
      subtitle: Control a character with real-time 3D physics and animations.
      description: A simple 3D character control example made with Doriax Engine.
      controls: |
        Move [W] [A] [S] [D] [←] [↑] [↓] [→] or gamepad
        Camera [LMB]
        Jump [Space]
